### ISSUE TITLE
Unavailable at conda channel

### ISSUE THREAD

**Issue by Michael-ljn** [polca/ScenarioLink#17]
Hey Romain, 

I tried to install via conda using: `conda install -c romainsacchi ab_plugin_scenariolink`, but it seems the package is not available at the `romainsacchi` channel. 

I successfully installed it via pip so it just to let you know some people might face this issue. 

Cheers,
Michael

**Comment by romainsacchi** [comment]
Sorry, I did not write that correctly. It's with dashes, not underscores.
Hence:

````
conda install -c romainsacchi ab-plugin-scenariolink
````

I corrected that. Thanks.
