### ISSUE TITLE
Naming convention e.g. "datapackage"

### ISSUE THREAD

**Issue by bsteubing** [polca/ScenarioLink#20]
I think we should improve the clarity of the naming, e.g. a database or SDF called datapackage_2023-09-18.xlsx really does not tell much about the content. I would suggest something like this:

For the **superstructure database** (if not superstructure, add the year)
"original database - IAM - scenario", e.g.
"ecoinvent 3.9.1 - IMAGE - SSP2-RCP19"

For the **scenario difference file** (SDF):
"SDF ecoinvent 3.9.1 - IMAGE - SSP2-RCP19.csv"

**Comment by romainsacchi** [comment]
`unfold 1.1.2` will now save SDF files with the proposed name structure: e.g., "ecoinvent 3.9.1 NAME.csv". But, NAME is given to `unfold` by [unfold_databases()](https://github.com/polca/ScenarioLink/blob/562ee454093250f4d28b7ec60661e1d533b824b5/ab_plugin_scenariolink/utils.py#L53C9-L53C9), which accepts an argument `superstructure_db_name` which is maybe not given (hence, the fallback to a generic "datapackage..." name). 

@marc-vdm  unfold_databases() is called by generate_databases(), itself called by _connect_signals(self). I do not know how things work here, but my suggestion is to make a name out of the concatenation of the fourth and fifth columns of the first table (e.g., "IMAGE" + "SSP2-RCP26")?

Once unfold_databases() receives a proper name argument, the SDF file will incorporate it, as well as the superstructure database name.

**Comment by marc-vdm** [comment]
I'll add that. Does that mean we don't need the name field anymore, or should `"IMAGE" + "SSP2-RCP26"` be the default name, and if the user adds a name to the field, we use that instead?

To summarize;
User chooses the Fold with `"IMAGE" + "SSP2-RCP26"`, then chooses some scenarios (>1) and chooses SDF, then we write a database to brightway named `"ecoinvent 3.9.1 - IMAGE - SSP2-RCP19"` and an SDF named `"ecoinvent 3.9.1 - IMAGE - SSP2-RCP19"` as `.csv` to a folder chosen by user. Unless, user chooses a different name.

I'll open a PR for this and #8 soon-ish with some screenshots to see if we agree on what it should look like.

**Comment by romainsacchi** [comment]
@marc-vdm Indeed, I think if a name is provided we use it, otherwise we fallback to concatenating the model and scenario values.
