### ISSUE TITLE
Create a button to clear the cache of unfold

### ISSUE THREAD

**Issue by romainsacchi** [polca/ScenarioLink#22]
`unfold` has a cache folder where ecoinvenit is pickled for faster runs the next time.
It has [a function to clear the cache](https://github.com/polca/unfold/blob/5ecc04bdf35faff1b17b48f0f2c2ea43533e5d86/unfold/unfold.py#L267C5-L267C5). I think we should have a button to run that function.

**Comment by marc-vdm** [comment]
@romainsacchi, where'd you like this button in the UI? Is this good (button would look like other buttons, just red here to make location clear) ?
![image](https://github.com/polca/ScenarioLink/assets/34626062/3c0cf5e3-1026-4ac7-bc9b-47ed60f12421)

**Comment by romainsacchi** [comment]
Yep, looks good.On 7 Oct 2023, at 21:39, Marc van der Meide ***@***.***> wrote:﻿
@romainsacchi, where'd you like this button in the UI? Is this good (button would look like other buttons, just red here to make location clear) ?
