### ISSUE TITLE
long term: Do MD5 hashing with the downloaded zip files

### ISSUE THREAD

**Issue by marc-vdm** [polca/ScenarioLink#27]
We should add the files' MD5 hash to the CSV and check if the downloaded file has the same MD5 as in the CSV before opening it so we know the download didn't fail.

SL should then either remove it from the cache or otherwise deal with this in a useful way

**Comment by romainsacchi** [comment]
Done. It checks the hash of the file after download and compares it to the hash given by Zenodo. If there's no match, the file is deleted right away and the retry dialog box appears.
