### ISSUE TITLE
Installing `0.0.7` in fresh environment is broken

### ISSUE THREAD

**Issue by marc-vdm** [polca/ScenarioLink#37]
Installing `0.0.7` in a new environment breaks AB

To reproduce:
```shell
conda create -n sl -c conda-forge --solver libmamba activity-browser -y
conda activate sl
conda install -c romainsacchi ab-plugin-scenariolink -y
activity-browser
```
which then gives:
```python
Traceback (most recent call last):
  File "C:\Users\meidemtvander\AppData\Local\miniconda3\envs\sl\Scripts\activity-browser-script.py", line 5, in <module>
    from activity_browser import run_activity_browser
  File "C:\Users\meidemtvander\AppData\Local\miniconda3\envs\sl\Lib\site-packages\activity_browser\__init__.py", line 6, in <module>
    from PySide2.QtCore import QSysInfo, __version__ as qt_version
ImportError: DLL load failed while importing QtCore: The specified module could not be found.
```

This is likely a dependency problem as when I install I get this, I'm not sure why Scenariolink would need to downgrade `qt-main`:
![image](https://github.com/polca/ScenarioLink/assets/34626062/63cf8ba8-0eb7-4c9a-8b34-491c3ef77288)

This probably broke in `0.0.7` as when I instead do `conda install -c romainsacchi ab-plugin-scenariolink=0.0.6 -y` in a fresh environment, AB works as expected. Note that downgrading to `0.0.6` in a broken environment will keep it broken, you need to re-install to fix it.

**Comment by romainsacchi** [comment]
I think this is coming from activity-browser, no?

if you do:

`````
conda create -n sl -c conda-forge --solver libmamba activity-browser -y
conda activate sl
activity-browser
`````

you do not get the error?

**Comment by romainsacchi** [comment]
The following:

`````
conda create -n sl -c conda-forge --solver libmamba activity-browser -y
conda activate sl
conda install -c romainsacchi ab-plugin-scenariolink -y
activity-browser
`````

does not cause an error on my end (MacOs).
Hence, I'd say it's an issue appearing on Windows computers, but I'm still not convinced the plugin is to blame.
Can you try the above without the line installing the plugin?

**Comment by marc-vdm** [comment]
That's right, I don't get the error when I only install AB, the environment breaks when I install the plugin.

It's probably some upstream dependency somewhere that breaks, but I haven't been able to figure it out.

**Comment by romainsacchi** [comment]
@marc-vdm Is this still an open issue?

**Comment by marc-vdm** [comment]
Whoops forgot to close this
