### ISSUE TITLE
Creating your own scenario 

### ISSUE THREAD

**Issue by MMahdi97** [polca/ScenarioLink#38]
Does anyone know how to create a new scenario not based on the premise's default scenario? 
How should the file be?
I mean instead of using the following scenario, create a new one.
![image](https://github.com/polca/ScenarioLink/assets/170021288/8838beb8-f8d8-40d2-ba13-7b69d9e137d8)
![image](https://github.com/polca/ScenarioLink/assets/170021288/1e76ab3b-4789-47ac-952e-8468a675ae44)

**Comment by marc-vdm** [comment]
Hi @MMahdi97, 

What kind of scenario would you like to use? You can create scenarios in Activity Browser for small changes or use premise for bigger changes. If you want to use Activity Browser, I would recommend using flow scenarios, for which we have a [video tutorial here](https://www.youtube.com/watch?v=3LPcpV1G_jg), if you want to use Premise, I would suggest starting with reading the [documentation](https://premise.readthedocs.io/en/latest/introduction.html). 

If this answered your question, please close the issue!
