### ISSUE TITLE
Checkboxes from the scenarios table should probably be unchecked by default

### ISSUE THREAD

**Issue by romainsacchi** [polca/ScenarioLink#5]

**Comment by marc-vdm** [comment]
That's no problem, but it's really difficult to create a '(un)check all' option in the UI. Do we still want it if that's the case?

**Comment by marc-vdm** [comment]
Or I could make the '(un)check all' in a right click (context) menu? That's not so hard

**Comment by romainsacchi** [comment]
I just meant that when the table appears, options should be checked out, because the likely that the user wants to install all scenarios is low I think (too many). No need for buttons I think.
