### ISSUE TITLE
Link to additional scenario info

### ISSUE THREAD

**Issue by romainsacchi** [polca/ScenarioLink#6]
(Long term)
It'd be good to have maybe a link that points to a resource explaining what the datapackage and scenarios are about (e.g., climate mitigation level, etc.). No precise idea on how that should look like yet.

**Comment by bsteubing** [comment]
+1
another idea to explore is to add a description on the brightway database level. This could be included in the Databases table in the AB once available and could summarize all the necessary details to understand what the database includes. I think this is quite important as for now I have only databases like this registered:

![image](https://github.com/polca/ScenarioLink/assets/33026150/a10a95d5-422c-4f9b-89e5-877a17a9c9af)

And to be honest I have no clue anymore what these databases are...

**Comment by romainsacchi** [comment]
There's now a dashboard to explore premise scenarios: https://premisedash-6f5a0259c487.herokuapp.com/

I could think of adding such link (not the actual link, but a label like "Scenario info") on each row in the scenario list (first table), for the user to click on.

**Comment by marc-vdm** [comment]
@romainsacchi If you add a column with the header `link` to the CSV with links to the dashboards, ScenarioLink will now show them. If no links column is present, nothing changes in ScenarioLink.

**Comment by romainsacchi** [comment]
@marc-vdm that does not seem to work though. I added a "link" column in the CSV, just before the Zenodo ID column, but cannot see it in AB.

**Comment by romainsacchi** [comment]
Maybe I misunderstood how this works, but it seems that `contextMenuEvent` does not get called anywhere in the code.

**Comment by romainsacchi** [comment]
Ah sorry, I misunderstood. Indeed, I right-clicked and was guided to the web.
