### ISSUE TITLE
Enable SDF export to custom path

### ISSUE THREAD

**Issue by marc-vdm** [polca/ScenarioLink#8]

**Comment by bsteubing** [comment]
I support that!

**Comment by romainsacchi** [comment]
@marc-vdm `unfold()` has now an `export_dir` argument to give a directory to export the SDF to. If unfilled, the current working directory is used. So you only need now to give [here](https://github.com/polca/ScenarioLink/blob/562ee454093250f4d28b7ec60661e1d533b824b5/ab_plugin_scenariolink/utils.py#L53) a directory path, I think.
